apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views as user_view

from .forms import CustomPasswordReset

app_name = 'users'

urlpatterns = [
    path('', user_view.register, name="register"),
    path('register/', user_view.register, name="register"),
    path('home/', user_view.home, name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='users/register/password_reset.html',
        email_template_name='users/register/password_reset_email.html',
        success_url='/users/reset_password_done',
        form_class=CustomPasswordReset),
        name="password_reset"
    ),
    path('reset_password_done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/register/password_reset_done.html'),
        name="password_reset_done"
    ),
    path('reset_password_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/register/password_reset_confirm.html',
        success_url='/password_reset_complete/'),
        name='password_reset_confirm'
 ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/register/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    url('activate/(?P<uidb64>[0-9A-Za-z\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_view.activate, name='activate'
    ),
]

on_boarding_task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.users.urls')),
    path('users/', include('apps.users.urls')),
    path('bookmarks/',include('apps.bookmarks.urls'))
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as user_view

from .forms import CustomPasswordReset

urlpatterns = [
    path('', user_view.register, name="register"),
    path('register/', user_view.register, name="register"),
    path('home/', user_view.home, name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='users/register/password_reset.html',
        form_class=CustomPasswordReset),
        name="password_reset"
    ),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/register/password_reset_done.html'),
        name="password_reset_done"
    ),
    path('reset_password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/register/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/register/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    url('activate/(?P<uidb64>[0-9A-Za-z\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_view.activate, name='activate'
    ),
]

apps/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self):
        return self.username

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text="Required")
    last_name = forms.CharField(max_length=30, required=True, help_text="Required")
    email = forms.EmailField(max_length=250, help_text="Required a valid email address")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_email(self):
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError((u'This email address is already in use. Try another'))
        return self.cleaned_data['email']

class CustomPasswordReset(PasswordResetForm):
    def clean(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            self.add_error('email', "No Account with this email Address")
        return super(CustomPasswordReset, self).clean()

apps/users/views.py
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .forms import SignUpForm
from .tokens import account_activation_token


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('users/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignUpForm()
    return render(request, 'users/register.html', {'form': form})


def home(request):
    return render(request, 'users/home.html')


def logout(request):
    logout(request)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist): 
        '''
        force_text accepts string as a argument if decoder gives something
        else it will raise Type Error and Value Error
        OverflowError will Occcur when uid value is be too large .
        '''
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

apps/users/templates/users/account_activation_email.html
{% autoescape off %}
  Hi {{ user.username }},
  Please click on the link to confirm your registration,
  http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

apps/users/templates/users/base.html
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> 
  </head>
  <body>
    <div class="container d-flex h-100">
      <div class="row justify-content-center">
        <div class="col-15">
          {% block main %}

          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

apps/users/templates/users/home.html
{% extends 'users/base.html' %}
{% block main %}
  {% if user.is_authenticated %}
        <div class="jumbotron text-center">

        <h3>Welcome to on boarding App</h3>
        <a href ="#"> Bookmark apps </a>
        </div>
        <p><a href="{% url 'users:logout' %}">logout</a></p>
  {% else %}
        <p>Account Created Successfully </p>
        <p>Now you can log in</p>
        <p><a href="{% url 'users:login' %}">LogIn</a></p>
  {% endif %}
{% endblock  %}

apps/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block main %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
          <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Log In</button>
            Forgot Password <a class="ml-2" href="{% url 'users:password_reset' %}">Reset Password</a>
          </div>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
      </small>
    </div>
  </div>
{% endblock  %}

apps/users/templates/users/logout.html
{% extends 'users/base.html' %}
{% block main %}
  <p> You have been successfully logout </p>
  <p> Do you want to Log In again </p>
  <button class="btn btn-success"><a href="{% url 'users:login' %}">Log In</a></button>
{% endblock %}

apps/users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block main %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Register</button>
  </form>
  <br>
  <div class="border-top pt-3">
    <small class="text-muted">
      Already have an Account ?<a class="ml-2" href="{% url 'users:login' %}">Login In</a>
    </small>
  </div>
{% endblock %}