apps/bookmarks/urls.py
from django.urls import path
from . import views

app_name = 'bookmarks'

urlpatterns = [
    path('folder/', views.FolderListView.as_view(), name="folders_list"),
    path('folder/<int:folder_id>/', views.BookmarkListView.as_view(), name='folder_detail'),
    path('create/', views.FolderCreateView.as_view(), name="folder_create"),
    path('<int:folder_id>/delete/', views.FolderDeleteView.as_view(), name="folder_delete"),
    path('folder/<int:folder_id>/create/', views.BookmarkCreateView.as_view(), name="bookmark_create"),
    path('folder/<int:bookmark_id>/delete', views.BookmarkDeleteView.as_view(), name='bookmark_delete'),
    path('<folder_id>/edit/', views.FolderUpdateView.as_view(), name="folder_update"),
]

apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views as user_view

from .forms import CustomPasswordReset

app_name = 'users'

urlpatterns = [
    path('', user_view.register, name="register"),
    path('register/', user_view.register, name="register"),
    path('home/', user_view.home, name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='users/register/password_reset.html',
        email_template_name='users/register/password_reset_email.html',
        success_url='/users/reset_password_done',
        form_class=CustomPasswordReset),
        name="password_reset"
    ),
    path('reset_password_done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/register/password_reset_done.html'),
        name="password_reset_done"
    ),
    path('reset_password_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/register/password_reset_confirm.html',
        success_url='/password_reset_complete/'),
        name='password_reset_confirm'
 ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/register/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    url('activate/(?P<uidb64>[0-9A-Za-z\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_view.activate, name='activate'
    ),
]

on_boarding_task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.users.urls')),
    path('users/', include('apps.users.urls')),
    path('bookmarks/',include('apps.bookmarks.urls'))
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as user_view

from .forms import CustomPasswordReset

urlpatterns = [
    path('', user_view.register, name="register"),
    path('register/', user_view.register, name="register"),
    path('home/', user_view.home, name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='users/register/password_reset.html',
        form_class=CustomPasswordReset),
        name="password_reset"
    ),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/register/password_reset_done.html'),
        name="password_reset_done"
    ),
    path('reset_password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/register/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/register/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    url('activate/(?P<uidb64>[0-9A-Za-z\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_view.activate, name='activate'
    ),
]

apps/bookmarks/models.py
from django.db import models
from model_utils.models import TimeStampedModel

from apps.users.models import User


class Folder(TimeStampedModel):
    name = models.CharField(max_length=50)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Bookmark(TimeStampedModel):
    folder = models.ForeignKey(Folder, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=150)
    url = models.URLField(max_length=230)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

apps/bookmarks/forms.py
from django.forms import ModelForm, forms

from .models import Folder, Bookmark


class FolderCreateForm(ModelForm):
    class Meta:
        model = Folder
        fields = ['name']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data['name'].capitalize()
        try:
            Folder.objects.get(created_by=self.user, name__iexact=name)
        except Folder.DoesNotExist:
            return name
        raise forms.ValidationError('Folder already exists.')

    def save(self, commit=True):
        folder = super().save(commit=False)
        folder.created_by = self.user
        folder.save()
        return folder


class BookmarkCreateForm(ModelForm):
    class Meta:
        model = Bookmark
        fields = ['name', 'url']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.folder = kwargs.pop('folder')
        super().__init__(*args, **kwargs)

    def clean_name(self):
        return self.cleaned_data['name'].capitalize()

    def clean(self):
        name = self.cleaned_data['name']
        url = self.cleaned_data['url']
        try:
            Bookmark.objects.get(created_by=self.user, name__iexact=name)
            self.add_error('name', 'Bookmark name already exists.')
        except Bookmark.DoesNotExist:
            try:
                Bookmark.objects.get(created_by=self.user, url__iexact=url)
                self.add_error('url', 'Url already exists.')
            except Bookmark.DoesNotExist:
                return super().clean()

    def save(self, commit=True):
        bookmark = super().save(commit=False)
        bookmark.created_by = self.user
        if self.folder == 'all':
            try:
                folder = Folder.objects.get(name='Uncategorized', created_by=self.user)
            except Folder.DoesNotExist:
                folder = Folder.objects.create(name="Uncategorized", created_by=self.user)
        else:
            folder = Folder.objects.filter(created_by=self.user).get(pk=self.folder)
        bookmark.folder = folder
        bookmark.save()
        return bookmark


class FolderUpdateForm(ModelForm):
    class Meta:
        model = Folder
        fields = ['name', ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data['name'].capitalize()
        count = Folder.objects.filter(created_by=self.user, name__iexact=name).count()
        if count == 0:
            return name
        raise forms.ValidationError('Folder already exists.')

apps/bookmarks/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404

from .models import Folder, Bookmark
from .forms import FolderCreateForm, BookmarkCreateForm, FolderUpdateForm


class FolderListView(LoginRequiredMixin, ListView):

    model = Folder
    template_name = 'bookmarks/folder_list.html'
    context_object_name = 'folders'
    ordering = ['name']


class BookmarkListView(LoginRequiredMixin, ListView):

    model = Bookmark
    template_name = 'bookmarks/folder_detail.html'
    context_object_name = 'bookmarks'
    ordering = ['name']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        folder = Folder.objects.filter(created_by=self.request.user).get(pk=self.kwargs['folder_id'])
        context["bookmarks"] = folder.bookmark_set.all()
        context["folder_id"] = folder.id
        return context


class FolderCreateView(LoginRequiredMixin, CreateView):
    form_class = FolderCreateForm
    template_name = 'bookmarks/folder_create_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        url = reverse('bookmarks:folders_list')
        return url


class BookmarkCreateView(LoginRequiredMixin, CreateView):
    form_class = BookmarkCreateForm
    template_name = 'bookmarks/bookmark_create_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        kwargs.update({'folder': self.kwargs['folder_id']})
        return kwargs

    def get_success_url(self):
        url = reverse('bookmarks:folders_list')
        return url


class FolderDeleteView(LoginRequiredMixin, DeleteView):
    model = Folder
    template_name = 'bookmarks/folder_delete_confirm.html'

    def get_object(self):
        id = self.kwargs.get('folder_id')
        return get_object_or_404(Folder, id=id)

    def get_success_url(self):
        return reverse('bookmarks:folders_list')

    def delete(self, request, *args, **kwargs):
        folder = self.get_object()

        if folder.name == "Uncategorized":
            for bookmark in folder.bookmark_set.all():
                bookmark.delete()
            folder.delete()
            return HttpResponseRedirect(reverse('bookmarks:folders_list'))

        if Folder.objects.filter(name='Uncategorized', created_by=self.request.user).exists():
            uncategorized_folder = Folder.objects.get(name="Uncategorized", created_by=self.request.user)
        else:
            uncategorized_folder = Folder.objects.create(name='Uncategorized', created_by=self.request.user)

        for bookmark in folder.bookmark_set.all():
            bookmark.folder = uncategorized_folder
            bookmark.save()
        folder.delete()
        return HttpResponseRedirect(reverse('bookmarks:folders_list'))


class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    template_name = 'bookmarks/bookmark_delete_confirm.html'

    def get_object(self):
        id = self.kwargs.get('bookmark_id')
        return get_object_or_404(Bookmark, id=id)

    def get_success_url(self):
        return reverse('bookmarks:folders_list')

        def get_queryset(self):
            qs = super().get_queryset()
            return qs.filter(created_by=self.request.user)


class FolderUpdateView(LoginRequiredMixin, UpdateView):
    model = Folder
    form_class = FolderUpdateForm
    template_name = 'bookmarks/folder_update_form.html'

    def get_object(self):
        id = self.kwargs.get('folder_id')
        return get_object_or_404(Folder, id=id)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_queryset(self):
        return Folder.objects.filter(created_by=self.request.user)

    def get_success_url(self):
        return reverse('bookmarks:folders_list')

apps/bookmarks/templates/bookmarks/base.html
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> 
  </head>
  <body>
     <nav class="navbar navbar-expand-md navbar-dark bg-primary">
                    <a class="navbar-brand" <a href ="{% url 'bookmarks:folders_list' %}">Bookmarks</a>
                    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                        aria-expanded="false" aria-label="Toggle navigation"></button>
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
                        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'bookmarks:folder_create' %}">Create Folder <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </nav>
       <div class="container d-flex h-100">
        {% block main %}

        {% endblock %}
    </div>
  </body>
</html>

apps/bookmarks/templates/bookmarks/bookmark_create_form.html
{% extends 'bookmarks/base.html' %}
{% load crispy_forms_tags %}
{% block main %}

    {{selected_folder}}

    <form method="post">{% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Create Bookmarks">
    </form>
{% endblock %}

apps/bookmarks/templates/bookmarks/bookmark_delete_confirm.html
{% extends 'bookmarks/base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

apps/bookmarks/templates/bookmarks/folder_create_form.html
{% extends 'bookmarks/base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form method="post">{% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Create Folder">
    </form>
{% endblock %}

apps/bookmarks/templates/bookmarks/folder_delete_confirm.html
{% extends 'bookmarks/base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

apps/bookmarks/templates/bookmarks/folder_detail.html
{% extends 'bookmarks/base.html' %}
{% block main %}
            
    <a class="link" href="{% url 'bookmarks:bookmark_create' folder_id %}"> Create Bookmark </a>

    {% for bookmark in bookmarks %}
        <div class='row'>
            <div class="card" style="width: 10rem; margin:20px" >
                <h5>Name :- {{ bookmark.name }}</h5>
                <a href="{{bookmark.url}}">{{bookmark.url}}</a>
                <br>
                <a href="{% url 'bookmarks:bookmark_delete' bookmark.id %}"> Delete </a>
                <br>
            </div>
        </div>
    {% endfor %}
{% endblock  %}

apps/bookmarks/templates/bookmarks/folder_list.html
{% extends 'bookmarks/base.html' %}
{% load static %}
{% block main %}
    {% for folder in folders %}
      <div class="row">
        <div class="card" style="width: 10rem; margin:20px">
          <img src="{% static "bookmarks/images/folder.jpg" %}" alt="My image" class="card-img-top">
          <div class="card-body">
          <h5 class="card-title">{{folder.name}}</h5>
          <p class="card-text">{{folder.created_by}}</p>
          <p> count :- {{ folder.bookmark_set.count }} </p>
          <a href="{{ folder.id }}" class="btn btn-primary">Open</a>
          <a href="{% url 'bookmarks:folder_delete' folder_id=folder.id %}"> Delete </a>
        </div>
      </div>
    {% endfor %}
{% endblock  %}

apps/bookmarks/templates/bookmarks/folder_update_form.html
{% extends 'bookmarks/folder_create_form.html' %}