apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views as user_view

from .forms import CustomPasswordReset

app_name = 'users'

urlpatterns = [
    path('', user_view.register, name="register"),
    path('register/', user_view.register, name="register"),
    path('home/', user_view.home, name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='users/register/password_reset.html',
        email_template_name='users/register/password_reset_email.html',
        success_url='/users/reset_password_done',
        form_class=CustomPasswordReset),
        name="password_reset"
    ),
    path('reset_password_done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/register/password_reset_done.html'),
        name="password_reset_done"
    ),
    path('reset_password_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/register/password_reset_confirm.html',
        success_url='/password_reset_complete/'),
        name='password_reset_confirm'
 ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/register/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    url('activate/(?P<uidb64>[0-9A-Za-z\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_view.activate, name='activate'
    ),
]

on_boarding_task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.users.urls')),
    path('users/', include('apps.users.urls')),
    path('bookmarks/',include('apps.bookmarks.urls'))
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as user_view

from .forms import CustomPasswordReset

urlpatterns = [
    path('', user_view.register, name="register"),
    path('register/', user_view.register, name="register"),
    path('home/', user_view.home, name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='users/register/password_reset.html',
        form_class=CustomPasswordReset),
        name="password_reset"
    ),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/register/password_reset_done.html'),
        name="password_reset_done"
    ),
    path('reset_password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/register/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/register/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    url('activate/(?P<uidb64>[0-9A-Za-z\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_view.activate, name='activate'
    ),
]

apps/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self):
        return self.username

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text="Required")
    last_name = forms.CharField(max_length=30, required=True, help_text="Required")
    email = forms.EmailField(max_length=250, help_text="Required a valid email address")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_email(self):
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError((u'This email address is already in use. Try another'))
        return self.cleaned_data['email']

class CustomPasswordReset(PasswordResetForm):
    def clean(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            self.add_error('email', "No Account with this email Address")
        return super(CustomPasswordReset, self).clean()

apps/users/views.py
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .forms import SignUpForm
from .tokens import account_activation_token


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('users/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignUpForm()
    return render(request, 'users/register.html', {'form': form})


def home(request):
    return render(request, 'users/home.html')


def logout(request):
    logout(request)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist): 
        '''
        force_text accepts string as a argument if decoder gives something
        else it will raise Type Error and Value Error
        OverflowError will Occcur when uid value is be too large .
        '''
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

apps/users/templates/users/register/password_reset.html
{% extends 'users/base.html' %}
  {% load crispy_forms_tags %}
    {% block main %}
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">submit</button>
      </form>
      <br>
    {% endblock %}

apps/users/templates/users/register/password_reset_complete.html
{% extends 'users/base.html' %}
  {% load crispy_forms_tags %}
    {% block main %}
      <p>
        Your password has been reset. You may go ahead and <a href="{% url 'users:login' %}">Login In</a> now.
      </p>
    {% endblock %}

apps/users/templates/users/register/password_reset_confirm.html
{% extends 'users/base.html' %}
  {% load crispy_forms_tags %}
    {% block main %}
      {% if validlink %}
        <h3>Change password</h3>
        <form method="post">
          {% csrf_token %}
          {{ form | crispy }}
          <button type="submit">Change password</button>
        </form>
      {% else %}
        <p>
          The password reset link is invalid because it's already visited.
        </p>
      {% endif %}
    {% endblock %}

apps/users/templates/users/register/password_reset_done.html
{% extends 'users/base.html' %}
  {% load crispy_forms_tags %}
    {% block main %}
      <p>
          We've emailed you instructions for resetting your password please check your inbox.</br>
          If you don't receive an email, please make sure you've entered the email address which you have used during registration, Or else Check Spam folder.
      </p>
    {% endblock %}

apps/users/templates/users/register/password_reset_email.html
{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
	
	{% trans "Thanks for using our site!" %}
	
	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
{% endautoescape %}